# Generated by Django 5.1.1 on 2024-11-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
